"""empty message

Revision ID: 021ede571776
Revises: a29f540343f9
Create Date: 2023-09-01 19:16:00.641982

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '021ede571776'
down_revision = 'a29f540343f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('clientes')
    op.drop_table('reservas')
    op.drop_table('cabana')
    op.drop_table('administradores')
    op.drop_table('proveedor')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('proveedor',
    sa.Column('_Proveedor__id', sa.INTEGER(), server_default=sa.text('nextval(\'"proveedor__Proveedor__id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('_Proveedor__nombre', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('_Proveedor__codigo', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('_Proveedor__cuit', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('_Proveedor__telefono', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('_Proveedor__email', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('_Proveedor__insumo', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('_Proveedor__id', name='proveedor_pkey')
    )
    op.create_table('administradores',
    sa.Column('_Administrador__id', sa.INTEGER(), server_default=sa.text('nextval(\'"administradores__Administrador__id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('_Administrador__codigo', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('_Administrador__nombre', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('_Administrador__puesto', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('_Administrador__id', name='administradores_pkey')
    )
    op.create_table('cabana',
    sa.Column('_Cabana__id', sa.INTEGER(), server_default=sa.text('nextval(\'"cabana__Cabana__id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('_Cabana__capacidad', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('_Cabana__tipo', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('_Cabana__nivel', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('_Cabana__codigo', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('_Cabana__id', name='cabana_pkey')
    )
    op.create_table('reservas',
    sa.Column('_Reserva__id', sa.INTEGER(), server_default=sa.text('nextval(\'"reservas__Reserva__id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('_Reserva__codigo', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('_Reserva__fecha_inicio', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('_Reserva__fecha_fin', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('_Reserva__num_cabana', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('_Reserva__codigo_cliente', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('_Reserva__id', name='reservas_pkey')
    )
    op.create_table('clientes',
    sa.Column('_Cliente__id', sa.INTEGER(), server_default=sa.text('nextval(\'"clientes__Cliente__id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('_Cliente__nombre', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('_Cliente__codigo', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('_Cliente__email', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('_Cliente__telefono', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('_Cliente__ciudad', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('_Cliente__id', name='clientes_pkey')
    )
    # ### end Alembic commands ###
