"""empty message

Revision ID: a29f540343f9
Revises: be8b1323f955
Create Date: 2023-09-01 19:15:10.784269

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a29f540343f9'
down_revision = 'be8b1323f955'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cabana',
    sa.Column('_Cabana__id', sa.Integer(), nullable=False),
    sa.Column('_Cabana__capacidad', sa.String(length=255), nullable=True),
    sa.Column('_Cabana__tipo', sa.String(length=255), nullable=True),
    sa.Column('_Cabana__nivel', sa.String(length=255), nullable=True),
    sa.Column('_Cabana__codigo', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('_Cabana__id')
    )
    op.create_table('clientes',
    sa.Column('_Cliente__id', sa.Integer(), nullable=False),
    sa.Column('_Cliente__nombre', sa.String(length=255), nullable=True),
    sa.Column('_Cliente__codigo', sa.String(length=255), nullable=True),
    sa.Column('_Cliente__email', sa.String(length=255), nullable=True),
    sa.Column('_Cliente__telefono', sa.String(length=255), nullable=True),
    sa.Column('_Cliente__ciudad', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('_Cliente__id')
    )
    op.create_table('proveedor',
    sa.Column('_Proveedor__id', sa.Integer(), nullable=False),
    sa.Column('_Proveedor__nombre', sa.String(length=255), nullable=True),
    sa.Column('_Proveedor__codigo', sa.String(length=255), nullable=True),
    sa.Column('_Proveedor__cuit', sa.String(length=255), nullable=True),
    sa.Column('_Proveedor__telefono', sa.String(length=255), nullable=True),
    sa.Column('_Proveedor__email', sa.String(length=255), nullable=True),
    sa.Column('_Proveedor__insumo', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('_Proveedor__id')
    )
    op.create_table('reservas',
    sa.Column('_Reserva__id', sa.Integer(), nullable=False),
    sa.Column('_Reserva__codigo', sa.String(length=255), nullable=True),
    sa.Column('_Reserva__fecha_inicio', sa.String(length=255), nullable=True),
    sa.Column('_Reserva__fecha_fin', sa.String(length=255), nullable=True),
    sa.Column('_Reserva__num_cabana', sa.String(length=255), nullable=True),
    sa.Column('_Reserva__codigo_cliente', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('_Reserva__id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reservas')
    op.drop_table('proveedor')
    op.drop_table('clientes')
    op.drop_table('cabana')
    # ### end Alembic commands ###
