"""empty message

Revision ID: be8b1323f955
Revises: 
Create Date: 2023-09-01 19:14:16.938113

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be8b1323f955'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('administradores',
    sa.Column('_Administrador__id', sa.Integer(), nullable=False),
    sa.Column('_Administrador__codigo', sa.String(length=255), nullable=True),
    sa.Column('_Administrador__nombre', sa.String(length=255), nullable=True),
    sa.Column('_Administrador__puesto', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('_Administrador__id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('administradores')
    # ### end Alembic commands ###
