"""empty message

Revision ID: c2d6cc2432f5
Revises: 808bc8b679c8
Create Date: 2023-09-07 18:37:57.903684

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2d6cc2432f5'
down_revision = '808bc8b679c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('administradores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))
        batch_op.drop_column('_Administrador__id')

    with op.batch_alter_table('cabana', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))
        batch_op.drop_column('_Cabana__id')

    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))
        batch_op.drop_column('_Cliente__id')

    with op.batch_alter_table('proveedor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))
        batch_op.drop_column('_Proveedor__id')

    with op.batch_alter_table('reservas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))
        batch_op.drop_column('_Reserva__id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('_Reserva__id', sa.INTEGER(), server_default=sa.text('nextval(\'"reservas__Reserva__id_seq"\'::regclass)'), autoincrement=True, nullable=False))
        batch_op.drop_column('id')

    with op.batch_alter_table('proveedor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('_Proveedor__id', sa.INTEGER(), server_default=sa.text('nextval(\'"proveedor__Proveedor__id_seq"\'::regclass)'), autoincrement=True, nullable=False))
        batch_op.drop_column('id')

    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('_Cliente__id', sa.INTEGER(), server_default=sa.text('nextval(\'"clientes__Cliente__id_seq"\'::regclass)'), autoincrement=True, nullable=False))
        batch_op.drop_column('id')

    with op.batch_alter_table('cabana', schema=None) as batch_op:
        batch_op.add_column(sa.Column('_Cabana__id', sa.INTEGER(), server_default=sa.text('nextval(\'"cabana__Cabana__id_seq"\'::regclass)'), autoincrement=True, nullable=False))
        batch_op.drop_column('id')

    with op.batch_alter_table('administradores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('_Administrador__id', sa.INTEGER(), server_default=sa.text('nextval(\'"administradores__Administrador__id_seq"\'::regclass)'), autoincrement=True, nullable=False))
        batch_op.drop_column('id')

    # ### end Alembic commands ###
